config/routes.rb
Rails.application.routes.draw do

 
 
  resources :products

  resources :clients do 
    member do 
      get 'confirmation'
    end 

    collection do 
      get 'login', action: :login 
      post 'login', action: :do_login 
      delete 'login', action: :logout
      get 'serch'
    end
  end 

  get 'sells/index'

  get 'sells/:id', to:  'sells#show'

end

app/models/client.rb
class Client < ActiveRecord::Base

	has_many :sells
	after_create :email_send

	def email_send


		puts "enviando email a #{self.email}"
	end

	validates :name, :email, presence: true
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i , message: "email valido" }



end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :sell
	
	validates :sell_id, :product_id, :quantity, presence: true
	validates :quantity, numericality: {greater_than: 0}
# sin s porque es personalizada la validación
	validate :validate_stock

	before_create :init_value
	after_create :update_stock

	after_destroy :add_stock

	def init_value
		self.value = self.quantity*self.product.price

	end

	def update_stock
		self.product.update_attribute(:quantity, self.product.quantity - self.quantity)

	end

	def validate_stock
		if self.quantity > self.product.quantity
			errors.add(:quantity, "no hay stock")
		end

	end

	def add_stock
		self.product.update_attribute(:quantity, self.product.quantity + self.quantity)
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	validates :ref, format: { with: /\A[0-9A-Z]+\z/ , message: "no es valido" }
	validates :size, length: { in: 1..10}
	 validates :size, inclusion: { in: %w(small medium large), message: "%{value} is not a valid size" }
	validates :price, numericality: {greater_than: 0}
	validates :ref, uniqueness:{message: "ya esta registrado!"}


	has_many :line_items
end

app/models/sell.rb
class Sell < ActiveRecord::Base
	validates :total, :client_id,  presence: true
	validates :total, numericality: {greater_or_equal_than: 0}


	has_many :line_items, after_add: :add_item, after_remove: :remove_item
	belongs_to :client

	def add_item(line_item)
		if line_item.valid?
			self.update_attribute(:total, self.total + line_item.value)
		end
	end

	def remove_item(line_item)
		if line_item.valid?
			self.update_attribute(:total, self.total - line_item.value)
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login_required
  	if session[:client_id].nil?
  	redirect_to login_clients_path,  
  	notice: 'el usuario no puede iniciar sesión'

  	end 
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

before_action :load_client, only: [:show,:edit,:update, :destroy]
  def index
  	@clients = Client.all 
  	#puts "#{clients.inspect}"
  end
  	def show
  		#@clients = Client.find(params[:id])
  	end

    def new
    	@client = Client.new 
    end

    def create 
    	params_filtered = params.require(:client).permit(:name,:email,:password)
    	@client = Client.new(params_filtered)
    
      	if @client.save
      		redirect_to clients_path
      	else
          render 'new' #render es comando para halar la vista en html
      
      	end
      end
    def edit 
        #@client = Client.find(params[:id])
    end
    def update 
     # @client = Client.find(params[:id]) #Los corchetes corresponden al número de find y params [:id] es el número del parametro
      params_filtered = params.require(:client).permit(:name, :email)
      
      if @client.update(params_filtered)
        redirect_to clients_path
    else 
      render 'edit' #redireccioneme a esta palntilla
    end 
  end
  def destroy 
   # @client = Client.find(params[:id])
    @client.destroy 
    redirect_to clients_path,
    notice: 'Usuario eliminado'

  end
  def load_client
    begin
      @client = Client.find(params[:id])
    rescue ActiveRecord::recordNotFound => e
      redirect_to clients_path,
      notice: 'El usuario no está resgitrado en la base de datos'
    end
  end
def login 
    @client = Client.new

   end

   def do_login 
    params_filtered = params.require(:client).permit(:email, :password)
    @client = Client.new(params_filtered)
    client_fetch = @client.login
    if @client.client_fetch
    session[:client_id] = client_field.id
    redirect_to products_path, notice: 'bienvenido a esto' 
    else
      flash[:error] = 'error al autenticarse'
      render 'login'
    end 
  end

  def logout
    session[:client_id] = nil 
    redirect_to login_users_path, notice: 'Se fue? Bueno. Buenas energías'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  before_action :login_required
  def index
  	@products = Product.all
  end

  def new
  	@products =Product.new
  end

  def show
  	@products= Product.find(params[:id])

  end

   def create 
    	params_filtered = params.require(:product).permit(:name,:ref, :price, :quantity, :size, :brand, :description, :color)
    	@product = Product.new(params_filtered)
    
      	if @product.save
      		redirect_to products_path
      	else
          render 'new' #render es comando para halar la vista en html
      	end
    end  
  def edit
      @product = Product.find(params[:id]) 	
  end

  def update 
      @product = Product.update(params[:id])
      params_filtered = params.require(:product).permit(:quantity, :description)

      if @client.update(params_filtered)
        redirect_to clients_path
      else 
        render 'edit'
      end
  end

  def destroy
    @product = Product.find(paramas[:id])
    @product.destroid
    redirect_to products_path,
  notice: 'El producto ha sido eliminado de su inventario'



end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
	def index
	@sells = Sell.all
	end
	def show
	@sells = Sell.find(params[:id])
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  	@user = User.all
  	puts "#{@user.inspect}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/clients/_form.html.erb
<%if !@client.errors.empty? %>
	<ol>
		<% @client.errors.full_messages.each do |msg| %> 
         <li> <%= msg %> </li>
         <%end%>
     </ol>
<%end%>

<%=  form_for @client do |f| %> <!-- Form_for es para un objeto explicito. El form_tag no va atado a nada-->

	<%= f.text_field :name %>
	<%= f.text_field :email %> <!--el igual significa que se muestre en el navegador, e decir que cuando está presente se muestra el html de este div--> 
	<% unless @client.persisted? %>
	<%= f.password_field :password %>
	<%end%>
    <%= f.submit %>

 <% end %>

app/views/clients/edit.html.erb
<h1> Editar Usuario </h1>

<%= render 'form' %> 

app/views/clients/index.html.erb
<h1>Lista de usuarios</h1>
<h3> El usuario ha sido elimado con exito </h3>
	
<table>
	<tr>
		<th>Nombre del usario</th>
		<th>Email</th>
		<th>Acciones</th>
	</tr>
	<% @clients.each do |client| %>
		<tr>
			<td><%= client.name %></td>
			<td><%= client.email %></td>
			<td><%= link_to 'Ver Detalle',  client %> |
			 <%= link_to 'Editar', edit_client_path(client) %>  
			<%= link_to 'Eliminar',  client, method: :delete %>   <!--la   data: {confirm: 'deseas eleminar el usuario'}  ruta de usuario se halla mediante la primera columna en la consola: rake routs-->
             </td>
		</tr>
	<% end %>
</table>
<p><%= "Hay #{@clients.size} clientes" %></p>

app/views/clients/new.html.erb
<h1> Nuevo Usuario </h1>

<%= render 'form' %> <!--ojo con los espacios-->


app/views/clients/show.html.erb
<h1>Detalle de usuario</h1>

<h2>Nombre:</h2> <%= @client.name%>

<h2>Email:</h2> <%= @client.email%>
<br>
<%= link_to 'Volver Al Listado', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pepito</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<% if session[:client_id] %>
<%= link_to 'cerrar sesión', login_clients_path, method: :delete%>
<%end%>
<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1 >Listado de productos  <style type="text/css">
  body {
    color: purple;
    background-color: #d8da3d }
  </style> </h1>

<p><%= "Hay #{@products.size} ventas registradas" %></p>
<table> 
	<tr>
		<th>Núm de Ref </th>
		<th>Cantidad</th>
		<th>Nombre</th>
		<th>Brand</th>
		<th>Descripción</th>
		<th>Acciones</th>
	</tr>
	<% @products.each do |products| %>
		<tr>
			<td><%= products.ref %></td>
			<td><%= products.quantity %></td>
			<td><%= products.name %></td>
			<td><%= products.brand %></td>
			<td><%= products.description %></td>
			<td><%= products.price %>
			<td><%= link_to 'Ver Detalle', url_for(controller: :products, action: :show, id: products.id) %>	
			<%= link_to 'Editar', edit_product_path(products) %> <!--OJO con la variable que se declara entre () ya que esta es la misma del .each do-->
			<%= link_to 'Eliminar', products, method: :delete %> 
		</td>
		</tr>
	<% end %>

</table> 
<p><%= "Hay #{@products.size} productos" %></p>

app/views/products/login.html.erb
<%=  form_for (@clients, url: {action: :login}, method: :post) do |p| %>
<div class='field'>
	<%= f.label  :email %> <br>
	<%= f.text_field :email %>
</div>

<div class='field'>
	<%= f.label  :password %> <br>
	<%= f.password_field :password %>
</div>

<% if flash[:error] %>
	<div class='error'>
		<%= flash[:error]%>
	</div>
    <%end%>
<div class='field'>
	<%= f.label  :password %> <br>
	<%= f.password_field :password %>
</div>

<div class='action'>
	<%= f.sumbit, "tocame rico" %> <br>
	
</div>
<%end%> 


app/views/products/new.html.erb
<%if !@products.errors.empty? %>
	<ol>
		<% @products.errors.full_messages.each do |msg| %> 
         <li> <%= msg %> </li>
         <%end%>
     </ol>
<%end%>
#hace las casillas para llenar el formulario
<%=  form_for @products do |p| %>

	<%= products.text_field :ref %>
	<%= productst.text_field :name %>
	<%= products.text_field :quantity %>
	<%= products.text_field :brand %>
    <%= products.text_field :description %>
	<%= products.text_field :price %>
	<%= f.submit %>

 <% end %>
 

app/views/products/show.html.erb
<h1>Detalle de Producto</h1>

<h2>Nombre:</h2> <%= @products.name %>

<h2>Ref:</h2> <%= @products.ref %>
<h2>Price:</h2> <%= @products.price %>

<br>
<%= link_to 'Volver Al Listado', products_path %> <!-- en las rutas no tiene index-->

app/views/sells/index.html.erb
<h1>VENTA</h1>

<p><%= "Hay #{@sells.size} ventas registradas" %></p>	
<table background: "blue">
	<tr>
		<th>Núm ID Venta </th>
		<th>Cliente</th>
		<th>Venta</th>
		<th>Cantidad</th>
		<th>Comentario</th>
		<th>Acciones</th>
	</tr>
	<% @sells.each do |sells| %>
		<tr>
			<td><%= sells.id %></td>
			<td><%= sells.total %></td>
			<td><%= sells.comment %></td>
			<td><%= link_to 'Ver Detalle', url_for(controller: :sells, action: :show, id: sells.id) %></td>

		</tr>
	<% end %>
</table>

app/views/sells/show.html.erb
<h1>Detalle de las ventas</h1>

<h2>Total:</h2> <%= @sells.total %>

<h2>Comentarios:</h2> <%= @sells.comment %>
<br>
<%= link_to 'Volver Al Listado', sells_index_path %>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Fihgjhfgjfjjf app/views/user/index.html.erb</p>